### ISSUE TITLE
DDR Change reason

### ISSUE THREAD

**Issue by kko-smol** [briansune/Tang-Mega-138K-AE350-Demo#1]
Hi
why did you change DDR and FLASH?
As I see SKHynix DDR3 can work at 1600 too

**Comment by briansune** [comment]
@kko-smol 

See the design and compare the maximum stable operation speed about bus interface rather than physical interface.
SKHynix physical speed does not mean anything when IF only runs at suboptimal speed.

**Comment by briansune** [comment]
@kko-smol 

I am going to close this issue as there are no actual issue referring to HDL designs nor the hardware setups.
